services:
    sql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: "sql-server"
        environment:
            MSSQL_SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks: 
            - "hoteis-rede"
        volumes: 
            - sql-db:source/volumes/ 
   
        
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
             ConnectionStrings__HotelDatabase: Server=sql-server;Database=Hoteis;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Trusted_Connection=False;
        container_name: hoteis-api
        depends_on:
            - sql-server
        ports:
            - "8080:5077"
        networks: 
            - "hoteis-rede"
networks:
    hoteis-rede:
        name: "hoteis-rede"
        
volumes:
    sql-db-hotel:

